
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/stackoverflow?serverTimezone=Asia/Seoul
    username: root
    password: 1234