spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/stackover_flow?serverTimezone=Asia/Seoul
#    username: root
#    password: 3525

    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create

  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type: 
            trace  
